#!/bin/bash

COLOR='\033[0;34m'
NC='\033[0m'
DIR="/tmp/aur-install/"

# create download directory
if [ ! -d $DIR ]; then
	echo -e "${COLOR}mkdir -pv $DIR${NC}"
	mkdir -pv $DIR
fi

cd $DIR

# clone package
echo -e "${COLOR}git clone http://aur.archlinux.org/$1.git${NC}"
git clone "http://aur.archlinux.org/$1.git"

cd $1

# install package
echo -e "${COLOR}makepkg -si${NC}"
makepkg -si

# remove download directory
echo -e "${COLOR}rm -r $DIR${NC}"
sudo rm -r $DIR
